language: ruby
dist: bionic
branches:
  only:
    - master
    - staging
    - trying
    - /^[\d.]+$/
    - /.+-stable$/
env:
  - "TEST_TOOL=rubygems"
  - "TEST_TOOL=bundler RGV=.."
rvm:
  - 2.6.4
jobs:
  include:
    - rvm: 2.6.4
      env: "TEST_TOOL=bundler RGV=.. BDV=master"
before_script:
  - util/ci.sh before_script
script:
  - util/ci.sh script
